x-api: &api
  image: thalessantanna/rinha-2026-java:0.2.0

services:
  api1:
    <<: *api
    hostname: api1
    environment:
      HTTP_SERVER: "NIO"
      UDS_PATH: /sockets/api1.sock
      DATASET_PATH: /resources/references-clustered.bin
      IVF_INDEX_PATH: /resources/references.idx
      VECTOR_INDEX: "${VECTOR_INDEX:-IVF}"
      IVF_CENTROIDS: "4096"
      IVF_NPROBE: "${IVF_NPROBE:-2}"
      BOUNDARY_FALLBACK: "${BOUNDARY_FALLBACK:-true}"
      BOUNDARY_FALLBACK_NPROBE: "${BOUNDARY_FALLBACK_NPROBE:-32}"
      PERF_LOG: "${PERF_LOG:-false}"
      MMAP_PREFETCH: "${MMAP_PREFETCH:-true}"
      MMAP_HUGEPAGE: "${MMAP_HUGEPAGE:-true}"
      IVF_EARLY_STOP: "${IVF_EARLY_STOP:-true}"
    volumes:
      - sockets:/sockets
    cpuset: "0"
    deploy:
      resources:
        limits:
          cpus: "0.44"
          memory: "165M"

  api2:
    <<: *api
    hostname: api2
    environment:
      HTTP_SERVER: "NIO"
      UDS_PATH: /sockets/api2.sock
      DATASET_PATH: /resources/references-clustered.bin
      IVF_INDEX_PATH: /resources/references.idx
      VECTOR_INDEX: "${VECTOR_INDEX:-IVF}"
      IVF_CENTROIDS: "4096"
      IVF_NPROBE: "${IVF_NPROBE:-2}"
      BOUNDARY_FALLBACK: "${BOUNDARY_FALLBACK:-true}"
      BOUNDARY_FALLBACK_NPROBE: "${BOUNDARY_FALLBACK_NPROBE:-32}"
      PERF_LOG: "${PERF_LOG:-false}"
      MMAP_PREFETCH: "${MMAP_PREFETCH:-true}"
      MMAP_HUGEPAGE: "${MMAP_HUGEPAGE:-true}"
      IVF_EARLY_STOP: "${IVF_EARLY_STOP:-true}"
    volumes:
      - sockets:/sockets
    cpuset: "1"
    deploy:
      resources:
        limits:
          cpus: "0.44"
          memory: "165M"

  lb:
    image: haproxy:3.0-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    cpuset: "2"
    deploy:
      resources:
        limits:
          cpus: "0.12"
          memory: "20M"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
